name: dockerized-test

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:


jobs:
  dockerized-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Build the image
      run: docker build . -t local/test -f Dockerfile.rie

    - name: Run tests
      uses: aws/containerized-test-runner-for-aws-lambda@v1
      with:
        suiteFileArray: '["./test/dockerized/*.json"]'
        dockerImageName: 'local/test'